DWAPlannerROS:
  #http://wiki.ros.org/dwa_local_planner

  min_vel_trans: -100.0
  max_vel_trans: 100.0

  min_vel_x: -0.2
  max_vel_x: 0.75

  min_vel_y: -0.1
  max_vel_y: 0.1

  max_vel_rot: 0.5
  min_vel_rot: -0.5

  acc_lim_trans: 100.0
  acc_lim_x: 10
  acc_lim_y: 1.0
  acc_lim_theta: 5.0

  trans_stopped_vel: 0.1
  theta_stopped_vel: 0.1

  # xy_goal_tolerance: 0.5
  # yaw_goal_tolerance: 0.34
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

  sim_time: 1
  sim_granularity: 0.3
  vx_samples: 20
  vy_samples: 10
  vth_samples: 20

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05

  forward_point_distance: 0.3
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 1.0

  oscillation_reset_dist: 0.1

  use_dwa: true

  prune_plan: false