obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.55,-0.2], [-0.55,0.2], [0.25, 0.2], [0.25, -0.2]]

transform_tolerance: 1.5
resolution: 0.05 

static_map_layer:
    map_topic: final_map
    subscribe_to_updates: true

2d_obstacles_layer:
  observation_sources: scan
  scan: {data_type: LaserScan,
    topic: shit,
    marking: true,
    clearing: true}

3d_obstacles_layer: 
  observation_sources: lidar camera
  lidar: {data_type: PointCloud2,
    topic: shit,
    min_obstacle_height: 0.1,
    max_obstacle_height: 0.2,
    marking: true,
    clearing: true}
  camera: {data_type: PointCloud2,
    topic: shit,
    min_obstacle_height: 0.1,
    max_obstacle_height: 0.2,
    marking: true,
    clearing: true}


inflation_layer:
    inflation_radius: 2.0
