obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[-0.45, -0.22], [-0.45, 0.22], [0.44, 0.22], [0.44, -0.22]]
footprint: [[-0.4, -0.22], [-0.4, 0.22], [0.4, 0.22], [0.4, -0.22]]

transform_tolerance: 0.5
resolution: 0.05 

static_map_layer:
    map_topic: projected_map
    subscribe_to_updates: true


# 2d_obstacles_layer:
#   observation_sources: scan
#   scan: {data_type: LaserScan,
#     topic: scan,
#     marking: true,
#     clearing: true}

#3d_obstacles_layer: 
#  observation_sources: lidar camera
#  lidar: {data_type: PointCloud2,
#    topic: ouster/points,
#    min_obstacle_height: 0.1,
#    marking: true,
#    clearing: true}
#  camera: {data_type: PointCloud2,
#    topic: camera/filtered_points,
#    min_obstacle_height: 0.1,
#    marking: true,
#    clearing: true}


# inflation_layer:
#   inflation_radius: 0.1
