local_costmap:
  global_frame: 2d_map
  robot_base_frame: base_link
  update_frequency: 5.0 
  publish_frequency: 2.0 

  static_map: false
  rolling_window: true
  width: 5
  height: 5
  cost_scaling_factor: 2.5

  plugins:
    - name: footprint_layer
      type: "costmap_2d::FootprintLayer"

  footprint_layer:
    observation_sources: haetae stretch obstacles
    haetae: {robot_id: haetae, sensor_frame: "", data_type: Polygon}
    spot: {robot: stretch, sensor_frame: "", data_type: Polygon}
    obstacles: {robot: obstacles, sensor_frame: "", data_type: Obstacle}
  