TebLocalPlannerROS:
  odom_topic: odom
  map_frame: 2d_map

#   # Trajectory
#   teb_autosize: True
#   dt_ref: 0.3
#   dt_hysteresis: 0.1
#   min_samples: 10
#   global_plan_overwrite_orientation: True
#   global_plan_viapoint_sep: -0.1
#   max_global_plan_lookahead_dist: 5.0
#   force_reinit_new_goal_dist: 1.0
#   feasibility_check_no_poses: 5
#   publish_feedback: False
#   shrink_horizon_backup: False
#   allow_init_with_backwards_motion: True
#   exact_arc_length: False
#   shrink_horizon_min_duration: 10

#   # Robot
#   max_vel_x: 0.75
#   max_vel_x_backwards: 0.4
#   max_vel_y: 0.1
#   max_vel_theta: 0.3
#   acc_lim_x: 0.3
#   acc_lim_y: 0.1
#   acc_lim_theta: 0.1
#   min_turning_radius: 0.0         # Not used in diff
#   wheelbase: 0.0                  # Not used in diff
#   cmd_angle_instead_rotvel: false # Not used in diff

#   is_footprint_dynamic: True
#   footprint_model:
#     type: "polygon"
#     vertices: [[-0.6, -0.22], [-0.6, 0.22], [0.44, 0.22], [0.44, -0.22]] # same as costmap_common_params.yaml
 
  # GoalTolerance
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.05 #0.05
  free_goal_vel: False

  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: True
  selection_alternative_time_cost: False
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  #selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 5.0
  selection_viapoint_cost_scale: 1.0
  
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  #roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  #obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
  #visualize_with_time_as_z_axis_scale: False
  viapoints_all_candidates: True
  switching_blocking_period: 0.0
  #delete_detours_backwards: True
  #max_ratio_detours_duration_best_duration: 3.0

  # Obstacles
  min_obstacle_dist: 0.2 #!!!!!!!!!!!!!!!!!!!!!!!! important # This value must also include our robot radius, since footprint_model is set to "point".
  inflation_dist: 0.0
  dynamic_obstacle_inflation_dist: 0.0
  include_dynamic_obstacles: True
  include_costmap_obstacles: True
  legacy_obstacle_association: False
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5.0
  costmap_obstacles_behind_robot_dist: 0.3
  obstacle_poses_affected: 30 # Not used
  #costmap_converter_plugin: "" 
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5.0

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.05

  weight_max_vel_x: 0.75
  weight_max_vel_y: 0.1
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_y: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 10 #1000.0
  weight_kinematics_forward_drive: 1.0 #1000.0
  weight_kinematics_turning_radius: 1.0
  weight_optimaltime: 10.0 # must be > 0
  weight_shortest_path: 0
  weight_obstacle: 20.0
  weight_inflation: 0.001
  weight_dynamic_obstacle: 1.0
  weight_dynamic_obstacle_inflation: 0.001
  weight_viapoint: 1.0
  weight_adapt_factor: 2.0

  # Recovery
  shrink_horizon_backup: False
  shrink_horizon_min_duration: 10
  oscillation_recovery: False
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10

  # Robot
  max_vel_x: 0.75
  max_vel_x_backwards: 0.5
  max_vel_theta: 0.15
  acc_lim_x: 0.3
  acc_lim_theta: 0.05
  min_turning_radius: 0.0         # Not used in diff
  cmd_angle_instead_rotvel: false # Not used in diff
  wheelbase: 0.0                  # Not used in diff
  footprint_model:
    type: "polygon"
    vertices: [[-0.45, -0.22], [-0.45, 0.22], [0.38, 0.22], [0.38, -0.22]] # same as costmap_common_params.yaml
  max_vel_y: 0.1
  acc_lim_y: 0.1
 
  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: True
  global_plan_viapoint_sep: -0.1
  max_global_plan_lookahead_dist: 5.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 5
  exact_arc_length: False
  publish_feedback: False
  min_samples: 10

